Issue26
hsfl-pltp/elm-review-pltp pull request #34
Opened 2022-04-27 18:50 UTC by mario-koehler

resolve #26

2022-04-28 08:28 UTC, jan-christiansen requested changes

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +exprToString : Node Expression -> String
Wird diese Funktion gar nicht verwendet?

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +debugMsg : Int -> Error scope
Wird diese Funktion gar nicht verwendet?

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +recordToError : Node Declaration -> Dict String Int -> ( String, ( String, Set string ) ) -> Maybe (Error {})
Hier kann die `Node` auch polymorph sein, da du nur die Positionsinformation benötigst. Ich würde sogar vorschlagen, hier immer nur den `Range` an die Funktionen weiterzugeben statt des gesamten `Node`.

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +recordToError : Node Declaration -> Dict String Int -> ( String, ( String, Set string ) ) -> Maybe (Error {})
Ich würde das Tupel schon vor dem Aufruf der Funktion zerlegen, das heißt, statt eines Argumentes `( String, ( String, Set string ) )` erhält diese Funktion drei Argumente `String`,  `String` und `Set string`.

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +recordToError : Node Declaration -> Dict String Int -> ( String, ( String, Set string ) ) -> Maybe (Error {})
Über das `string` hatten wir ja schon gesprochen. Argumente von Funktionen gern polymorph definieren, wenn möglich. Ggf. aber auch einmal darüber nachdenken, ob man dann nicht weniger Informationen an die Funktion übergeben kann. Hier könnte man zum Beispiel statt der gesamten Menge vielleicht auch nur die Anzahl der Elemente übergeben.

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +    }
Hatten wir ja vorhin schon besprochen, gern einmal versuchen, für Vorkommen von `String` Datentypen einzuführen, also zum Beispiel `type VarName = VarName String`.

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +    case Dict.get key context.functionNodes of
Witzigerweise hältst du dich hier selbst nicht an die Regel, die du gerade implementierst hast : )

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +functionToErrorList context key value list =
`key`, `value` und `list` sind hier keine guten Variablennamen.

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +            Nothing
Hier würde ich `andThen` verwenden, ähnlich zu dem Beispiel unter https://package.elm-lang.org/packages/elm/core/latest/Maybe#andThen

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +                                            Just ( t, Set.insert field oldSet )
Hier würde ich `Maybe.map` und vielleicht sogar `Tuple.mapSecond` verwenden.

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +                Expression.Application (fun :: parameters) ->
Ich würde hier den Begriff `arguments` statt `parameters` verwenden, `parameters` wird meist im Kontext von formalen Parametern verwendet, während `arguments` meist bei tatsächlichen Parametern verwendet wird.

2022-04-28 08:28 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +destructedRecordPattern : Context -> ( String, Node Pattern ) -> Maybe (Error {})
Auch hier brauchst du vom `Context` gar nicht alle Komponenten.

2022-04-28 20:19 UTC, mario-koehler commented on review/src/NoMinimalRecordAccess.elm
> +exprToString : Node Expression -> String
Die hatte ich bisher vergessen zu entfernen.

2022-04-28 20:19 UTC, mario-koehler commented on review/src/NoMinimalRecordAccess.elm
> +debugMsg : Int -> Error scope
Die hatte ich bisher vergessen zu entfernen.

2022-04-28 20:20 UTC, mario-koehler commented on review/src/NoMinimalRecordAccess.elm
> +recordToError : Node Declaration -> Dict String Int -> ( String, ( String, Set string ) ) -> Maybe (Error {})
Ich werde die entsprechende Range mitgeben.

2022-04-28 20:24 UTC, mario-koehler commented on review/src/NoMinimalRecordAccess.elm
> +recordToError : Node Declaration -> Dict String Int -> ( String, ( String, Set string ) ) -> Maybe (Error {})
schwierig, da diese Funktion in einem `filterMap` benutzt wird, das Tupel ist nur ein Element der entsprechenden Liste über die `filterMap` läuft.

2022-04-28 20:25 UTC, mario-koehler commented on review/src/NoMinimalRecordAccess.elm
> +recordToError : Node Declaration -> Dict String Int -> ( String, ( String, Set string ) ) -> Maybe (Error {})
ich werde nochmal die Funktionen durchschauen, ob ich ähnliche Fälle finde.

2022-04-28 20:25 UTC, mario-koehler commented on review/src/NoMinimalRecordAccess.elm
> +functionToErrorList context key value list =
wird geändert

2022-04-29 07:06 UTC, mario-koehler commented on review/src/NoMinimalRecordAccess.elm
> +recordToError : Node Declaration -> Dict String Int -> ( String, ( String, Set string ) ) -> Maybe (Error {})
Hier das gleiche Problem wie beim Tupel zerlegen. Da recordToError als Funktion an die `filterMap` Funktion übergeben wird, brauche ich hier das Tupel mit dem `Set` und kann nicht direkt ein `Int` übergeben stattdessen

2022-04-29 07:20 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +recordToError : Node Declaration -> Dict String Int -> ( String, ( String, Set string ) ) -> Maybe (Error {})
Alles klar, da habe ich nicht aufgepasst. In Haskel nutzt man für solche Fälle `uncurry : (a -> b -> c) -> (a,b) -> c` in Elm haben sie die Funktion aber (aus ganz verständlichen Gründen) entfernt, da der Code dadurch nicht unbedingt übersichtlicher wird.

2022-04-29 07:30 UTC, mario-koehler commented on review/src/NoMinimalRecordAccess.elm
> +    }
Ich hebe mir das für den nächsten Commit auf, da ich einige der Strings durch einen anderen vorhanden Typ ersetzen werde, z.B `TypeAnnotation` oder ähnliches.

2022-04-29 16:08 UTC, mario-koehler commented on review/src/NoMinimalRecordAccess.elm
> +    }
Alternative: Ich werde eine oder mehrere Datenstrukturen als Wrapper schreiben, um die Strings als spezielle Typen umzusetzen.

2022-05-03 06:15 UTC, jan-christiansen requested changes

2022-05-03 06:15 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +                                |> .typeAnnotation
Hier finde ich die Pipes eher ungeeignet, der Ausdruck ist ja nicht sehr komplex und es handelt sich eigentlich auch nicht um eine Pipeline, die eine Struktur wie eine Liste verarbeitet.

2022-05-03 06:15 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +                                |> List.map (\( n, t ) -> ( n, ( t, Set.empty ) ))
Hier könntest du noch `Tuple.mapSecond` verwenden.

2022-05-03 06:15 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +                                recordAlias
Das Pattern musst du nicht klammern.

2022-05-03 06:15 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +                        Just (destructedError node record (List.length list) numberOfFields)
Ich würde an `destructedError` den `RecordAlias` übergebenen nicht den `String`.

2022-05-03 06:55 UTC, jan-christiansen requested changes

2022-05-03 06:55 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +            functionScope
Hier kannst du das Pattern Matching jetzt im Argument machen statt im `let`.

2022-05-03 06:55 UTC, jan-christiansen commented on review/src/NoMinimalRecordAccess.elm
> +    in
Hier kannst du das Pattern Matching jetzt im Argument machen statt im `let`.

2022-05-03 07:02 UTC, merged