Update eta-reduction-rule to traverse Expressions for variable
hsfl-pltp/elm-review-pltp pull request #43
Opened 2022-05-22 19:44 UTC by mario-koehler

resolve #42

2022-05-24 08:09 UTC, jan-christiansen requested changes

2022-05-24 08:09 UTC, jan-christiansen commented on review/src/Visitor.elm
> +                )
Im Modul taucht ja immer wieder `List.foldl (+) 0` auf, dann sollte man das auch einmal als Funktion rausziehen. Nach dem Umbau wird die Funktion sicher anders aussehen, aber rausziehen kann man sie sicher trotzdem.

2022-05-26 16:06 UTC, mario-koehler commented on review/src/Visitor.elm
> +countAppearancesOfString string node =
CHECK

2022-05-26 16:07 UTC, mario-koehler commented on review/src/Visitor.elm
> +                )
nach Umbau blieb nur `List.concat (List.map ...)` übrig, was sich noch durch `List.concatMap` zusammenfassen ließ.

2022-05-27 05:43 UTC, jan-christiansen approved these changes

2022-05-27 05:43 UTC, merged